import React, { createContext, useState, useContext } from 'react'

const LanguageContext = createContext()

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.track': 'Track Package',
    'nav.pricing': 'Pricing',
    'nav.wallet': 'Wallet',
    'nav.orders': 'Orders',
    'nav.support': 'Support',
    'nav.referral': 'Referral',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.logout': 'Logout',
    'nav.profile': 'Profile',
    'nav.admin': 'Admin',

    // Home Page
    'home.hero.title': 'Ship from UK, USA & China to Kenya',
    'home.hero.subtitle': 'Fast, affordable, and reliable shipping services',
    'home.hero.cta': 'Get Started',
    'home.hero.track': 'Track Package',

    'home.howitworks': 'How It Works',
    'home.step1': 'Shop from your favorite retailers',
    'home.step2': 'Ship to our warehouse',
    'home.step3': 'We consolidate & deliver',
    'home.step4': 'Receive in Kenya',

    'home.retailers': 'Supported Retailers',
    'home.markets': 'Our Markets',
    'home.testimonials': 'What Our Customers Say',
    'home.pricing.title': 'Transparent Pricing',
    'home.pricing.description': 'See exactly what you pay before you ship',
    'home.pricing.calculate': 'Calculate Now',

    // Authentication
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.name': 'Full Name',
    'auth.phone': 'Phone Number',
    'auth.referralCode': 'Referral Code (Optional)',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.loginHere': 'Login here',
    'auth.registerHere': 'Register here',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.loginSuccess': 'Login successful!',
    'auth.registerSuccess': 'Registration successful!',
    'auth.invalidCredentials': 'Invalid email or password',

    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.warehouseAddress': 'Your Warehouse Address',
    'dashboard.activeOrders': 'Active Orders',
    'dashboard.walletBalance': 'Wallet Balance',
    'dashboard.referralEarnings': 'Referral Earnings',
    'dashboard.recentOrders': 'Recent Orders',
    'dashboard.newOrder': 'New Order',
    'dashboard.topupWallet': 'Top Up Wallet',

    // Orders
    'orders.title': 'My Orders',
    'orders.new': 'New Order',
    'orders.filter': 'Filter',
    'orders.filterByStatus': 'Filter by Status',
    'orders.filterByMarket': 'Filter by Market',
    'orders.noOrders': 'No orders yet',
    'orders.orderNumber': 'Order #',
    'orders.market': 'Market',
    'orders.status': 'Status',
    'orders.date': 'Date',
    'orders.amount': 'Amount',
    'orders.actions': 'Actions',
    'orders.view': 'View',
    'orders.pending': 'Pending',
    'orders.processing': 'Processing',
    'orders.inTransit': 'In Transit',
    'orders.delivered': 'Delivered',
    'orders.failed': 'Failed',
    'orders.cancelled': 'Cancelled',

    // Pricing
    'pricing.title': 'Shipping Calculator',
    'pricing.market': 'Market of Origin',
    'pricing.weight': 'Weight (kg)',
    'pricing.dimensions': 'Dimensions',
    'pricing.length': 'Length (cm)',
    'pricing.width': 'Width (cm)',
    'pricing.height': 'Height (cm)',
    'pricing.shipping': 'Shipping Speed',
    'pricing.economy': 'Economy',
    'pricing.express': 'Express',
    'pricing.insurance': 'Add Insurance',
    'pricing.declaredValue': 'Declared Value (KES)',
    'pricing.calculate': 'Calculate',
    'pricing.results': 'Pricing Breakdown',
    'pricing.baseCost': 'Base Shipping Cost',
    'pricing.volumetric': 'Volumetric Weight',
    'pricing.actual': 'Actual Weight',
    'pricing.surcharge': 'Express Surcharge',
    'pricing.insuranceCost': 'Insurance Cost',
    'pricing.estimatedDuty': 'Estimated Customs Duty',
    'pricing.total': 'Total',
    'pricing.inUSD': 'in USD',
    'pricing.inKES': 'in KES',

    // Exchange Rates
    'exchange.title': 'Exchange Rates',
    'exchange.liveRates': 'Live Exchange Rates',
    'exchange.usdToKes': 'USD to KES',
    'exchange.gbpToKes': 'GBP to KES',
    'exchange.swap': 'Swap',
    'exchange.historicalNote': 'Historical rates',

    // Wallet
    'wallet.balance': 'Wallet Balance',
    'wallet.deposit': 'Deposit Funds',
    'wallet.method': 'Payment Method',
    'wallet.mpesa': 'M-Pesa',
    'wallet.card': 'Credit/Debit Card',
    'wallet.paypal': 'PayPal',
    'wallet.phone': 'Phone Number',
    'wallet.amount': 'Amount (KES)',
    'wallet.deposit': 'Deposit',
    'wallet.history': 'Transaction History',
    'wallet.type': 'Type',
    'wallet.date': 'Date',
    'wallet.status': 'Status',
    'wallet.noTransactions': 'No transactions yet',

    // New Order
    'neworder.title': 'Create New Order',
    'neworder.market': 'Select Market',
    'neworder.retailer': 'Retailer',
    'neworder.retailerPlaceholder': 'Select a retailer',
    'neworder.other': 'Other (specify)',
    'neworder.description': 'Package Description',
    'neworder.weight': 'Estimated Weight (kg)',
    'neworder.dimensions': 'Dimensions (Optional)',
    'neworder.shippingSpeed': 'Shipping Speed',
    'neworder.insurance': 'Add Insurance',
    'neworder.promoCode': 'Promo or Referral Code',
    'neworder.estimate': 'Estimated Cost',
    'neworder.submit': 'Create Order',
    'neworder.costEstimate': 'Cost Estimate',

    // Consolidation
    'consolidation.title': 'Package Consolidation',
    'consolidation.description': 'Combine multiple packages to save on shipping',
    'consolidation.selectPackages': 'Select packages to consolidate',
    'consolidation.estimatedSavings': 'Estimated Savings',
    'consolidation.request': 'Request Consolidation',
    'consolidation.requests': 'Consolidation Requests',
    'consolidation.status': 'Status',
    'consolidation.noPackages': 'No packages available for consolidation',

    // Track Package
    'track.title': 'Track Your Package',
    'track.placeholder': 'Enter tracking number',
    'track.search': 'Track',
    'track.trackingNumber': 'Tracking Number',
    'track.status': 'Status',
    'track.lastUpdate': 'Last Update',
    'track.estimatedDelivery': 'Estimated Delivery',
    'track.notFound': 'Package not found',
    'track.timeline': 'Tracking Timeline',

    // Warehouse Addresses
    'warehouse.title': 'Your Warehouse Addresses',
    'warehouse.uk': 'United Kingdom',
    'warehouse.usa': 'United States',
    'warehouse.china': 'China',
    'warehouse.copy': 'Copy Address',
    'warehouse.copied': 'Copied to clipboard',
    'warehouse.instructions': 'Instructions',
    'warehouse.instruction1': 'Use this address when shopping online',
    'warehouse.instruction2': 'Include your SC code in the recipient name',
    'warehouse.instruction3': 'Wait for email confirmation when package arrives',

    // Prohibited Items
    'prohibited.title': 'Prohibited Items',
    'prohibited.search': 'Search for an item',
    'prohibited.allowed': 'This item is allowed',
    'prohibited.restricted': 'This item is restricted',
    'prohibited.reason': 'Reason',
    'prohibited.categories': 'Item Categories',
    'prohibited.dangerousGoods': 'Dangerous Goods',
    'prohibited.electronics': 'Electronics',
    'prohibited.liquids': 'Liquids & Chemicals',
    'prohibited.valuable': 'Valuable Items',
    'prohibited.other': 'Other Restrictions',

    // Support
    'support.title': 'Support Tickets',
    'support.create': 'Create New Ticket',
    'support.subject': 'Subject',
    'support.description': 'Description',
    'support.priority': 'Priority',
    'support.high': 'High',
    'support.medium': 'Medium',
    'support.low': 'Low',
    'support.attach': 'Attach File',
    'support.submit': 'Submit Ticket',
    'support.myTickets': 'My Tickets',
    'support.ticketId': 'Ticket ID',
    'support.reply': 'Reply',
    'support.send': 'Send',
    'support.noTickets': 'No support tickets yet',

    // Referral
    'referral.title': 'Referral Program',
    'referral.code': 'Your Referral Code',
    'referral.copy': 'Copy Code',
    'referral.share': 'Share With',
    'referral.whatsapp': 'WhatsApp',
    'referral.email': 'Email',
    'referral.stats': 'Your Stats',
    'referral.totalReferrals': 'Total Referrals',
    'referral.completed': 'Completed',
    'referral.earned': 'Total Earned',
    'referral.promotion': 'KES 50 for every successful referral',
    'referral.history': 'Referral History',
    'referral.name': 'Name',
    'referral.dateReferred': 'Date Referred',
    'referral.status': 'Status',
    'referral.earnings': 'Earnings',
    'referral.pending': 'Pending',
    'referral.completed': 'Completed',

    // Admin
    'admin.title': 'Admin Dashboard',
    'admin.overview': 'Overview',
    'admin.users': 'Users',
    'admin.orders': 'Orders',
    'admin.revenue': 'Revenue',
    'admin.tickets': 'Support Tickets',
    'admin.totalUsers': 'Total Users',
    'admin.activeOrders': 'Active Orders',
    'admin.revenueToday': 'Revenue Today',
    'admin.revenueWeek': 'Revenue This Week',
    'admin.revenueMonth': 'Revenue This Month',
    'admin.pendingPackages': 'Pending Packages',
    'admin.ordersChart': 'Orders Over Time',
    'admin.revenueChart': 'Revenue Chart',
    'admin.ordersByMarket': 'Orders by Market',
    'admin.userManagement': 'User Management',
    'admin.search': 'Search users...',
    'admin.editRole': 'Edit Role',
    'admin.orderManagement': 'Order Management',
    'admin.bulkUpdate': 'Bulk Status Update',
    'admin.selectStatus': 'Select new status',
    'admin.updateSelected': 'Update Selected',
    'admin.revenueReport': 'Revenue Report',
    'admin.dateRange': 'Date Range',
    'admin.byMarket': 'By Market',
    'admin.export': 'Export CSV',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.areYouSure': 'Are you sure?',
    'common.required': 'This field is required',
    'common.invalidEmail': 'Please enter a valid email',
    'common.passwordTooShort': 'Password must be at least 6 characters',
    'common.passwordsDoNotMatch': 'Passwords do not match',
    'common.copyright': '© 2024 SwiftCargo. All rights reserved.',
    'common.followUs': 'Follow Us',
    'common.contactUs': 'Contact Us',
    'common.about': 'About Us',
    'common.privacy': 'Privacy Policy',
    'common.terms': 'Terms of Service',
  },
  sw: {
    // Navigation
    'nav.home': 'Nyumbani',
    'nav.dashboard': 'Dashibodi',
    'nav.track': 'Fuatilia Pakiti',
    'nav.pricing': 'Bei',
    'nav.wallet': 'Mkoba',
    'nav.orders': 'Maagizo',
    'nav.support': 'Msaada',
    'nav.referral': 'Kumbukizi',
    'nav.login': 'Ingia',
    'nav.register': 'Jisajili',
    'nav.logout': 'Toka',
    'nav.profile': 'Wasifu',
    'nav.admin': 'Msimamizi',

    // Home Page
    'home.hero.title': 'Tuma kutoka UK, USA na China hadi Kenya',
    'home.hero.subtitle': 'Huduma ya utoaji ya haraka, nafuu, na kutegemewa',
    'home.hero.cta': 'Anza',
    'home.hero.track': 'Fuatilia Pakiti',

    'home.howitworks': 'Jinsi inavyofanya kazi',
    'home.step1': 'Nunua kutoka kwa ndege zako',
    'home.step2': 'Tuma kwenye ghala letu',
    'home.step3': 'Tunaunganisha na kudelivery',
    'home.step4': 'Pokea huko Kenya',

    'home.retailers': 'Ndege Zilizotengea',
    'home.markets': 'Soko Letu',
    'home.testimonials': 'Mtazamo wa Wateja Wetu',
    'home.pricing.title': 'Bei Iliyoonyesha',
    'home.pricing.description': 'Ona halisi utakachokipiga kabla ya kujenga',
    'home.pricing.calculate': 'Hesabu Sasa',

    // Authentication
    'auth.email': 'Anwani ya Barua Pepe',
    'auth.password': 'Neno la Siri',
    'auth.confirmPassword': 'Thibitisha Neno la Siri',
    'auth.name': 'Jina Kamili',
    'auth.phone': 'Namba ya Simu',
    'auth.referralCode': 'Nambari ya Kumbukizi (Hiyari)',
    'auth.login': 'Ingia',
    'auth.register': 'Jisajili',
    'auth.noAccount': 'Huna akaunti?',
    'auth.haveAccount': 'Je, tayari una akaunti?',
    'auth.loginHere': 'Ingia hapa',
    'auth.registerHere': 'Jisajili hapa',
    'auth.forgotPassword': 'Umesahau Neno la Siri?',
    'auth.loginSuccess': 'Kuingia kumefanikiwa!',
    'auth.registerSuccess': 'Usajili umefanikiwa!',
    'auth.invalidCredentials': 'Barua pepe au neno la siri batili',

    // Dashboard
    'dashboard.welcome': 'Karibu',
    'dashboard.warehouseAddress': 'Anwani Yako ya Ghala',
    'dashboard.activeOrders': 'Maagizo Yanayoendelea',
    'dashboard.walletBalance': 'Usawa wa Mkoba',
    'dashboard.referralEarnings': 'Kupokea kwa Kumbukizi',
    'dashboard.recentOrders': 'Maagizo ya Karibuni',
    'dashboard.newOrder': 'Agizo Jipya',
    'dashboard.topupWallet': 'Kamilisha Mkoba',

    // Orders
    'orders.title': 'Maagizo Yangu',
    'orders.new': 'Agizo Jipya',
    'orders.filter': 'Sieve',
    'orders.filterByStatus': 'Sieve kwa Hali',
    'orders.filterByMarket': 'Sieve kwa Soko',
    'orders.noOrders': 'Hakuna maagizo bado',
    'orders.orderNumber': 'Agizo #',
    'orders.market': 'Soko',
    'orders.status': 'Hali',
    'orders.date': 'Tarehe',
    'orders.amount': 'Kiasi',
    'orders.actions': 'Vitendo',
    'orders.view': 'Angalia',
    'orders.pending': 'Insubiri',
    'orders.processing': 'Inachakatwa',
    'orders.inTransit': 'Njiani',
    'orders.delivered': 'Imekamatia',
    'orders.failed': 'Imefeli',
    'orders.cancelled': 'Imefutwa',

    // Pricing
    'pricing.title': 'Kikokotoo cha Utoaji',
    'pricing.market': 'Soko la Asili',
    'pricing.weight': 'Uzani (kg)',
    'pricing.dimensions': 'Vipimo',
    'pricing.length': 'Urefu (cm)',
    'pricing.width': 'Upana (cm)',
    'pricing.height': 'Urefu (cm)',
    'pricing.shipping': 'Kasi ya Utoaji',
    'pricing.economy': 'Uchumi',
    'pricing.express': 'Haraka',
    'pricing.insurance': 'Ongeza Bima',
    'pricing.declaredValue': 'Thamani ya Kutangazwa (KES)',
    'pricing.calculate': 'Hesabu',
    'pricing.results': 'Kuharibiana kwa Bei',
    'pricing.baseCost': 'Bei ya Utoaji wa Msingi',
    'pricing.volumetric': 'Uzani wa Volumetric',
    'pricing.actual': 'Uzani Halisi',
    'pricing.surcharge': 'Malipo ya Haraka Zaidi',
    'pricing.insuranceCost': 'Gharama ya Bima',
    'pricing.estimatedDuty': 'Kodi ya Kukamatia Inayotakikana',
    'pricing.total': 'Jumla',
    'pricing.inUSD': 'katika USD',
    'pricing.inKES': 'katika KES',

    // Exchange Rates
    'exchange.title': 'Viwango vya Kubadilisha',
    'exchange.liveRates': 'Viwango vya Mabadiliko Yaliyomo',
    'exchange.usdToKes': 'USD hadi KES',
    'exchange.gbpToKes': 'GBP hadi KES',
    'exchange.swap': 'Badilisha',
    'exchange.historicalNote': 'Viwango vya kihistoria',

    // Wallet
    'wallet.balance': 'Usawa wa Mkoba',
    'wallet.deposit': 'Kuweka Pesa',
    'wallet.method': 'Njia ya Malipo',
    'wallet.mpesa': 'M-Pesa',
    'wallet.card': 'Kadi ya Mikakati/Karatasi',
    'wallet.paypal': 'PayPal',
    'wallet.phone': 'Namba ya Simu',
    'wallet.amount': 'Kiasi (KES)',
    'wallet.deposit': 'Kuweka',
    'wallet.history': 'Historia ya Muamala',
    'wallet.type': 'Aina',
    'wallet.date': 'Tarehe',
    'wallet.status': 'Hali',
    'wallet.noTransactions': 'Hakuna muamala bado',

    // New Order
    'neworder.title': 'Fungua Agizo Jipya',
    'neworder.market': 'Chagua Soko',
    'neworder.retailer': 'Muuzaji wa Rejareja',
    'neworder.retailerPlaceholder': 'Chagua muuzaji',
    'neworder.other': 'Nyingine (eleza)',
    'neworder.description': 'Kueleza kwa Pakiti',
    'neworder.weight': 'Uzani Unatarajiwa (kg)',
    'neworder.dimensions': 'Vipimo (Hiyari)',
    'neworder.shippingSpeed': 'Kasi ya Utoaji',
    'neworder.insurance': 'Ongeza Bima',
    'neworder.promoCode': 'Nambari ya Promosi au Kumbukizi',
    'neworder.estimate': 'Gharama Inayotakikana',
    'neworder.submit': 'Fungua Agizo',
    'neworder.costEstimate': 'Tahmini ya Gharama',

    // Consolidation
    'consolidation.title': 'Ujumuishaji wa Pakiti',
    'consolidation.description': 'Unganisha pakiti nyingi ili kuokoa kwenye utoaji',
    'consolidation.selectPackages': 'Chagua pakiti za kuunganisha',
    'consolidation.estimatedSavings': 'Akiba Inayotakikana',
    'consolidation.request': 'Omba Ujumuishaji',
    'consolidation.requests': 'Ombi za Ujumuishaji',
    'consolidation.status': 'Hali',
    'consolidation.noPackages': 'Hakuna pakiti inayopatikana kwa ujumuishaji',

    // Track Package
    'track.title': 'Fuatilia Pakiti Yako',
    'track.placeholder': 'Ingiza namba ya kufuatilia',
    'track.search': 'Fuatilia',
    'track.trackingNumber': 'Namba ya Kufuatilia',
    'track.status': 'Hali',
    'track.lastUpdate': 'Sasisho la Mwisho',
    'track.estimatedDelivery': 'Utoaji Unatarajiwa',
    'track.notFound': 'Pakiti haijapatikana',
    'track.timeline': 'Msingi wa Kufuatilia',

    // Warehouse Addresses
    'warehouse.title': 'Anwani Zako za Ghala',
    'warehouse.uk': 'Uingereza',
    'warehouse.usa': 'Maarikani',
    'warehouse.china': 'China',
    'warehouse.copy': 'Kunakili Anwani',
    'warehouse.copied': 'Kunakili kwenye clipboard',
    'warehouse.instructions': 'Maelezo',
    'warehouse.instruction1': 'Tumia anwani hii wakati wa kununua mtandaoni',
    'warehouse.instruction2': 'Jumuisha nambari yako ya SC katika jina la pokea',
    'warehouse.instruction3': 'Subiri ujumbe wa kumkutania wakati pakiti ikifika',

    // Prohibited Items
    'prohibited.title': 'Vitu Vilivyokatazwa',
    'prohibited.search': 'Tafuta kitu',
    'prohibited.allowed': 'Kitu hiki kiruhusiwi',
    'prohibited.restricted': 'Kitu hiki kina mipango',
    'prohibited.reason': 'Sababu',
    'prohibited.categories': 'Kategoria za Kitu',
    'prohibited.dangerousGoods': 'Bidhaa Hatari',
    'prohibited.electronics': 'Elektroniki',
    'prohibited.liquids': 'Vinywaji na Kemikali',
    'prohibited.valuable': 'Vitu vya Thamani',
    'prohibited.other': 'Vikwazo vingine',

    // Support
    'support.title': 'Tiketi za Msaada',
    'support.create': 'Fungua Tiketi Mpya',
    'support.subject': 'Kichwa',
    'support.description': 'Kueleza',
    'support.priority': 'Kipaumbele',
    'support.high': 'Juu',
    'support.medium': 'Katikati',
    'support.low': 'Chini',
    'support.attach': 'Ambatisha Faili',
    'support.submit': 'Wasilisha Tiketi',
    'support.myTickets': 'Tiketi Zangu',
    'support.ticketId': 'Tiketi ID',
    'support.reply': 'Jibu',
    'support.send': 'Tuma',
    'support.noTickets': 'Hakuna tiketi za msaada bado',

    // Referral
    'referral.title': 'Programu ya Kumbukizi',
    'referral.code': 'Nambari Yako ya Kumbukizi',
    'referral.copy': 'Kunakili Nambari',
    'referral.share': 'Shiriki Na',
    'referral.whatsapp': 'WhatsApp',
    'referral.email': 'Barua Pepe',
    'referral.stats': 'Takwimu Zako',
    'referral.totalReferrals': 'Jumla ya Kumbukizi',
    'referral.completed': 'Ilikamilika',
    'referral.earned': 'Jumla ya Kupokea',
    'referral.promotion': 'KES 50 kwa kila kumbukizi kamilifu',
    'referral.history': 'Historia ya Kumbukizi',
    'referral.name': 'Jina',
    'referral.dateReferred': 'Tarehe ya Kumbukizi',
    'referral.status': 'Hali',
    'referral.earnings': 'Kupokea',
    'referral.pending': 'Insubiri',
    'referral.completed': 'Ilikamilika',

    // Admin
    'admin.title': 'Dashibodi ya Msimamizi',
    'admin.overview': 'Muhtasari',
    'admin.users': 'Watumiaji',
    'admin.orders': 'Maagizo',
    'admin.revenue': 'Mapato',
    'admin.tickets': 'Tiketi za Msaada',
    'admin.totalUsers': 'Jumla ya Watumiaji',
    'admin.activeOrders': 'Maagizo Yanayoendelea',
    'admin.revenueToday': 'Mapato Leo',
    'admin.revenueWeek': 'Mapato Juma Hili',
    'admin.revenueMonth': 'Mapato Mwezi Huu',
    'admin.pendingPackages': 'Pakiti Zinazoinsubiri',
    'admin.ordersChart': 'Maagizo Kwa Muda',
    'admin.revenueChart': 'Chati ya Mapato',
    'admin.ordersByMarket': 'Maagizo kwa Soko',
    'admin.userManagement': 'Usimamizi wa Watumiaji',
    'admin.search': 'Tafuta watumiaji...',
    'admin.editRole': 'Hariri Jukumu',
    'admin.orderManagement': 'Usimamizi wa Maagizo',
    'admin.bulkUpdate': 'Sasisho la Wingi la Hali',
    'admin.selectStatus': 'Chagua hali mpya',
    'admin.updateSelected': 'Sasisha Kuchaguliwa',
    'admin.revenueReport': 'Ripoti ya Mapato',
    'admin.dateRange': 'Eneo la Tarehe',
    'admin.byMarket': 'Kwa Soko',
    'admin.export': 'Kuhamisha CSV',

    // Common
    'common.loading': 'Inakamata...',
    'common.error': 'Hitilafu',
    'common.success': 'Kumefanikiwa',
    'common.save': 'Hifadhi',
    'common.cancel': 'Ghairi',
    'common.delete': 'Futa',
    'common.edit': 'Hariri',
    'common.back': 'Nyuma',
    'common.close': 'Funga',
    'common.search': 'Tafuta',
    'common.filter': 'Sieve',
    'common.sort': 'Panga',
    'common.export': 'Kuhamisha',
    'common.import': 'Kuagiza',
    'common.yes': 'Ndiyo',
    'common.no': 'Hapana',
    'common.confirm': 'Thibitisha',
    'common.areYouSure': 'Je, una hakika?',
    'common.required': 'Uga huu unahitajika',
    'common.invalidEmail': 'Tafadhali ingiza barua pepe halali',
    'common.passwordTooShort': 'Neno la siri lazima liwe na herufi angalau 6',
    'common.passwordsDoNotMatch': 'Maneneo ya siri hayalingani',
    'common.copyright': '© 2024 SwiftCargo. Haki zote zimehifadhiwa.',
    'common.followUs': 'Tufuate',
    'common.contactUs': 'Wasiliana Nasi',
    'common.about': 'Kuhusu Sisi',
    'common.privacy': 'Sera ya Faragha',
    'common.terms': 'Masharti ya Huduma',
  },
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'en')

  const changeLanguage = (lang) => {
    localStorage.setItem('language', lang)
    setLanguage(lang)
  }

  const t = (key, defaultValue = key) => {
    return translations[language]?.[key] || translations.en[key] || defaultValue
  }

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
