-- ============================================================
-- Migration 049 — drop legacy public.run_parcels (audit F-16).
--
-- `run_parcels` was the v1 join table between last_mile_runs and
-- packages. Replaced by `last_mile_run_parcels` (mig audit_012) which
-- adds the position column needed for ordered rider stops. Verified
-- before dropping:
--
--     select count(*) from public.run_parcels;
--     -- 0 rows in live prod
--
-- And no live route code references it:
--
--     grep -rn "FROM run_parcels\\b\\|INTO run_parcels\\b\\|UPDATE run_parcels\\b"
--     # zero hits in routes/, utils/, middleware/
--
-- All 16 query sites that join the rider-run table use
-- `last_mile_run_parcels` (routes/lastMile.js).
-- ============================================================

DROP TABLE IF EXISTS public.run_parcels CASCADE;
